language: ruby
rvm:
- 2.2
script:
- bundle exec rspec spec
deploy:
  provider: heroku
  api_key:
    secure: 'mjIFvaZxXVVzG2RKdkI87s32x048Uwbg6yOw9W3CsX715Ouok8V9nmamW908IM7/p17ZFdT3HRxlq97E4oojjjxVsGC69svozrcm4V18JMmXlWOPJDdDAYwFZOqMhy8YYfFzOPNH6Ju5mTkAXcpXU0hAc1BaTqMySGGB1eFQl66B2wVR8g3bCu0ngiGhynkQYcy+Br9xB8vdLuOVI6qPASA1ZqX6aCUsrlc2zxwY4QdOcLmDAV/sM5/QsJuiqtVzxrfqqm7hT2izlaq0SjyZVb/muJDHS/Srf6n11ekUxfsSYACYZqfopJC1FnzN03KdvAwIg/2jDf7X7SCTUOtWltD7xkF/b3ufxhDkhHCprkYq581wQ7KNJ8K7ilc6CdalwbtUK8kMd+izc6N8yD+EffAKkuqTCerdwdwV2oM7R6kmOdk4J2FG7EBuhNK6+A92EhSdkgIAJN0RpWawEGCzlno+FzDbpH9/rPFiBgqmc82ByAifsBnNLJf1VDpBKTHKzbOjWKggYvMlbw0Vrh6QxJuLhymc0vFcluxsm/LQ7/Ty5l21IZkC8Lfdn1+ZuUDBxmUhDrRGgT0Qv6aeIllw9Mvsr3ekYxzcUydAV5ek2LroQs6LLgzORfxxlvtVyFQv99fsNv6+tOi0jyiofsv6KqJbJ8FUJ5NBDrWDZQGa+l4='
  app: 'triviapreguntados'
