language: ruby
rvm:
- 2.2
script:
- bundle exec rspec spec
deploy:
  provider: heroku
  api_key:
    secure: 'IYKDxUMlcK6KZw/AqcwXknhlFLbgpdxzLc2SaLtekqrrFw6uM/mBx+Jcbfq7NnzNnLmk72q+grh9YtfBMC6LelgydQMTE77sSuJ+re/HE+RpcM/1jP0fMYGa/fhwyX9JT4lxzMIWcDw4jqHEs9XnbrYZBeHyBDsYZnCfqaXXed6drGuPNtUk4woS1Y0DOcMb7kvJ+awv5rjHDK2RRvxSXNFy9LUv3HKn6SAFglRguTNLTQ2eIFzA6cVXrdQaffjmh2/D9OOAwZTQWQdjojsLO/7HMy9SoE1wM2/W4G/VOwCX/csodnuZ8LNP1fEWMyoZwNy4+IC+3kEHfSrGPqNF1D8vUHPCdh3yxdDZ6Yhkj7bvOocFEo6RGydoRfqijZBbxqjsDGkjH8qwq5YUAq+I5k/vzTJ9yuFzph5eSYldgd4jgN5hczaNt+g61kaWLWpY9zlFyMxxUN1q5xT9SMU65VS/5kCM0zaGJ4KqHQ6jk1x0p8d8SOyzY8nYUJf/Ylfm3hId/ikczLDnH6ZCwdxC0gmfOVXIORY/Hfb1arw5i8Gwc1Sq3AJAOwMInFOq9RkOlUOho0kCCPwDimik4bKII4vjd6gWzj5j01iYSTWlxRsdiW9yi98xOl/f1Tut3SrxHMyijyGIP3JD/v2o2BrkcLWBPmVxfyUv8of+k1wRz/0='
  app: 'triviapreguntados'
